name: Deploying docker registry
on:
  workflow_dispatch:
    inputs:
        vpc:
            required: true
            default: qa
            type: choice
            options: [qa,prod]

jobs:
  deploy:
    uses: ./.github/workflows/deploy-registry-lib.yml
    with:
      vpc: ${{inputs.vpc}}