name: Docker registry-lib
on:
  workflow_call:
    inputs:
      Universe:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
permissions:
  id-token: write
  contents: read
  actions: read
jobs:
  deploy-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import Environment File
        run: |
          if [ "${{ inputs.Universe }}" == "ci" ] || [ "${{ inputs.Universe }}" == "cert" ] || [ "${{ inputs.Universe }}" == "anon" ]; then
            echo "ENVFILE=Environments.env" >> $GITHUB_ENV
            echo "ENVNAME=QA" >> $GITHUB_ENV
          else
            echo "ENVFILE=ProdEnvironments.env" >> $GITHUB_ENV
            echo "ENVNAME=PROD" >> $GITHUB_ENV
          fi

      - name: Import Environment Variables
        uses: cardinalby/export-env-action@v2
        with:
          envFile: '${{ env.ENVFILE }}'
          expand: 'true'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env[format('aws_environment_{0}', env.ENVNAME)] }}:role/emojigitrole
          role-session-name: emojiDockerSession
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploying docker registry
        run: |
          aws cloudformation deploy \
          --stack-name emoji-docker-registry-test \
          --template-file ops/cfn/docker-registry.cfn.yml \
          --parameter-overrides                           \
            ECRRepositoryName=emodb/emoji-test                 \
          --no-fail-on-empty-changeset                    \
          --tags                                          \
            bv:nexus:team="${{ env.TEAM }}"                       \
            bv:nexus:vpc="${{ env.ENVNAME }}"                         \
            bv:system=emodb                               \
            bv:nexus:service=emoji                        \
            bv:nexus:role=docker-registry                 \
            bv:nexus:owner="${{ env.TEAM }}"                      \
            bv:nexus:access=none                          \
            bv:nexus:costcenter="${{ env.TEAM }}"                 \
            bv:nexus:datatype=intellectualproperty        \
            bv:nexus:env="${{ env.ENVNAME }}"                         \
          --region ${{ env.AWS_REGION }}
          
      - name: Alert to slack
        uses: 8398a7/action-slack@v3
        if: ${{ always() }}
        with:
          status: ${{ job.status }}
          fields: repo,message,job,workflow
          author_name: The workflow at ${{github.repository}} on branch ${{github.ref_name}} is ${{job.status}}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
