name: Deploy registry
on: 
    workflow_dispatch:
        inputs:
            Universe:
                description: 'Universe to deploy'
                default: 'ci'
                type: choice
                options: [ci, cert, anon, uat, bazaar]
                required: true
            AWS_REGION:
                description: 'AWS region to deploy'
                default: 'us-east-1'
                type: choice
                options: [us-east-1]

permissions:
    id-token: write
    contents: read
    actions: read
                  
jobs:
  deploy-docker-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

    #   - name: Checkout repository with library file
    #     uses: actions/checkout@v3
    #     with:
    #       repository: kpnssreeram/Library
    #       path: libscript

      - name: Fetch data 
        run: |
            label=$(python ./EmojiLib.py getVpcByUniverse "${{inputs.Universe}}")
            account_id=$(python ./EmojiLib.py getAccountIdByUniverse "${{inputs.Universe}}")
            echo "EnvTag=$label" >> $GITHUB_ENV
            echo "AccId=$account_id" >> $GITHUB_ENV
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            role-to-assume: arn:aws:iam::${{env.AccId}}:role/emojigitrole
            role-session-name: emojiDeployDockerSession
            aws-region: ${{ inputs.AWS_REGION }}

      - name: Deploy registry
        run: |
            aws cloudformation deploy                                               \
            --stack-name emoji-docker-registry-test                                 \
            --template-file cd ops/cfn/docker-registry.cfn.yml                         \
            --parameter-overrides                                                   \
                ECRRepositoryName=emodb/emoji-test                                      \
                --no-fail-on-empty-changeset                                            \
            --tags                                                                  \
                bv:nexus:team=$(python ./EmojiLib.py getTags "team")          \
                bv:nexus:vpc=${{env.EnvTag}}                                            \
                bv:system=emodb                                                         \
                bv:nexus:service=$(python ./EmojiLib.py getTags "service")    \
                bv:nexus:role=docker-registry                                           \
                bv:nexus:owner=$(python ./EmojiLib.py getTags "team")         \
                bv:nexus:access=none                                                    \
                bv:nexus:costcenter=$(python ./EmojiLib.py getTags "team")    \
                bv:nexus:datatype=intellectualproperty                                  \
                bv:nexus:env=${{env.EnvTag}}                                         \
            --region ${{inputs.AWS_REGION}}

      - name: Alert to slack
        uses: 8398a7/action-slack@v3
        if: ${{ always() }}
        with:
          status: ${{ job.status }}
          fields: repo,message,job,workflow
          author_name: The workflow at ${{ github.repository }} on branch ${{ github.ref_name }} is ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}