name: Deploying docker registry
on:
  workflow_dispatch:
    inputs:
      Universe:
        description: 'Universe to deploy'
        default: 'ci'
        type: choice
        options: [ci, cert, anon, uat, bazaar]
        required: true
jobs:
  call-Libregistry:
    uses: ./.github/workflows/deploy-registry-lib.yml
    with:
      Universe: ${{inputs.Universe}}