name: Deploying docker registry
on:
  workflow_dispatch:
    inputs:
       Universe:
        description: 'Universe to deploy'
        default: 'ci'
        type: choice
        options: [ci, cert, anon, uat, bazaar]
        required: true
jobs:
  callDeployRegistryLib:
    uses: ./.github/workflows/deploy-registry-lib.yml
    with:
      Universe: ${{inputs.Universe}}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}