name: emoji-release
on:
  workflow_dispatch:
    inputs:
      Universe:
        description: 'Universe to deploy'
        default: 'ci'
        type: choice
        options: [ci, cert, anon, uat, bazaar]
        required: true
      ReleaseVersion:
        description: 'Release version'
        default: '0.53'
        required: true
      DevelopmentVersion:
        description: 'Development version'
        default: '0.54-SNAPSHOT'
        required: true 
jobs:
  callEmojiRelease:
    uses: ./.github/workflows/emoji-release-lib.yml
    with:
      Universe: ${{ inputs.Universe }}
      ReleaseVersion: ${{ inputs.ReleaseVersion }}
      DevelopmentVersion: ${{ inputs.DevelopmentVersion }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
