name: emoji-release
on:
  workflow_dispatch:
    inputs:
        Universe:
            description: 'Universe to deploy '
            default: 'ci'
            type: choice
            options: [ci, cert, anon, uat, bazaar]
            required: true
jobs:
  read:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils
      - name: Get Release Version
        id: get-release-version
        run: |
          RELEASE_VERSION=$(xmllint --xpath "//*[local-name()='parent']/*[local-name()='version']/text()" pom.xml | sed 's/-SNAPSHOT//g')
          echo "release-version=$RELEASE_VERSION" >> $GITHUB_OUTPUT
      - name: Get Major Version
        id: get-major-version
        run: |
          MAJOR_VERSION=$(echo "${{ steps.get-release-version.outputs.release-version }}" | cut -d'.' -f1)
          echo "major-version=$MAJOR_VERSION" >> $GITHUB_OUTPUT
      - name: Get Development Version
        id: get-dev-version
        run: |
          MINOR_VERSION=$(echo "${{ steps.get-release-version.outputs.release-version }}" | cut -d'.' -f2)
          DEV_VERSION="${{ steps.get-major-version.outputs.major-version }}.$(($MINOR_VERSION + 1))-SNAPSHOT"
          echo "dev-version=$DEV_VERSION" >> $GITHUB_OUTPUT
      - name: print
        run:
            echo ${{ steps.get-dev-version.outputs.dev-version }}

  call-emoji-release:
    needs: read
    uses: ./.github/workflows/emoji-release-lib.yml
    with:
    #   Universe: ${{inputs.Universe}}
      ReleaseVersion: ${{ needs.read.outputs.release-version }}
      DevelopmentVersion: ${{ needs.read.outputs.dev-version }}
      