name: Deploy Secrets

on:
  workflow_dispatch:
    inputs:
      Universe:
        description: 'Universe to deploy'
        default: 'ci'
        type: choice
        options: [ci, cert, anon, uat, bazaar]
        required: true
      ApiKey:
        description: 'API Key value'
        type: string
        required: false
      AccessToken:
        description: 'Access Token value'
        type: string
        required: false
      AWS_REGION:
        description: 'AWS region to deploy'
        default: 'us-east-1'
        type: choice
        options: [us-east-1]
      tags:
        description: 'Comma separated list of tags'
        default: 'deploydocker'
        type: choice
        options: [deploydocker, deploysecrets, anon, uat, bazaar]
        required: true

jobs:
  callSecretsLib:
    uses: ./.github/workflows/EmojiLib.yml
    with:
      Universe: ${{ inputs.Universe }}
      AWS_REGION: ${{ inputs.AWS_REGION }}
      tags: ${{ inputs.tags }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
