name: emoji-release
on:
    workflow_dispatch:
        inputs:
            emoji:
                description: 'Emoji to release'
                required: true
                default: '🎉'
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
                  registry-url: 'https://registry.npmjs.org'
            - run: npm ci
            - run: npm run build
            - run: npm publish --access public
              