name: emoji_branch_WF

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Git branch name to checkout'  
        default: 'main' 
        type: choice
        options:
          - main
          - develop
          - feature/*
      universe:
        description: 'Universe to deploy'
        default: 'ci'
        type: choice
        options:
          - ci
          - cert
          - anon
          - uat
          - bazaar
                      
      # api_key:
      #   description: 'API Key value'
      #   type: password
      #   required: true
        
      # access_token:
      #   description: 'Access Token value' 
      #   type: password
      #   required: true
        
      # datadog_key:
      #   description: 'Datadog Key value'
      #   type: password
      #   required: true
  

env:
    # ENVIRONMENT_TAG: ${{fromJson(needs.label-discovery.outputs.vpc-data)[github.event.inputs.universe]}}
    STACK_NAME: ${{github.event.inputs.universe}}-emoji-secret
    AWS_REGION: ap-south-1
    TEAM: emodb-dev@bazaarvoice.com
    SERVICE: emoji
    DATATYPE: client+personal
  
permissions:
  id-token: write
  contents: read

jobs:
  retrieve_stk_info:
    runs-on: ubuntu-latest
    steps:
        - name: environment_print
          run: echo ${{github.event.inputs.universe}}
        - name: configure aws credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::549050352176:role/emojigitrole
            role-session-name: samplerolesession
            aws-region: ${{ env.AWS_REGION }}
