name: Deploy Emoji

on:
  workflow_dispatch:
    inputs:
      Universe:
        description: 'Universe to deploy'
        default: 'ci'
        type: choice
        options: [ci, cert, anon, uat, bazaar]
        required: true

      aws_environment:
        description: 'Which environment to deploy'
        default: 'QA'
        type: choice
        options: [QA, PROD]
        required: true

      ApiKey:
        description: 'API Key value'
        type: string
        required: true

      AccessToken:
        description: 'Access Token value'
        type: string
        required: true

env:
  SERVICE: emoji

jobs:
  deploy:
    uses: ./.github/workflows/Librarydeploy.yml
    with:
      Universe: ${{ github.event.inputs.Universe }}
      aws_environment: ${{ github.event.inputs.aws_environment }}
      ApiKey: ${{ github.event.inputs.ApiKey }}
      AccessToken: ${{ github.event.inputs.AccessToken }}

  clouddeploy:
      runs-on: ubuntu-latest
      needs: deploy
      steps:
        - name: Deploy Secrets
          run: |
            cd ops/cfn
            aws cloudformation deploy \
              --stack-name ${{ env.STACK_NAME }} \
              --template-file secrets.cfn.yml \
              --region ${{ env.AWS_REGION }} \
              --capabilities CAPABILITY_IAM \
              --no-fail-on-empty-changeset \
              --parameter-overrides \
                Universe=${{ inputs.Universe }} \
                AccessToken=${{ env.Access_Token }} \
                ApiKey=${{ env.API_PASSWORD }} \
              --tags \
                bv:nexus:team=${{ env.TEAM }} \
                bv:nexus:vpc=1233 \
                bv:system=emodb \
                bv:nexus:service=${{ vars.SERVICE }} \
                bv:nexus:owner=${{ env.TEAM }} \
                bv:nexus:costcenter=${{ env.TEAM }} \
                bv:nexus:datatype=${{ env.DATATYPE }} \
                bv:nexus:env=1234
