name: emoji_branch_WF

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Git branch name to checkout'  
        default: 'main' 
        type: choice
        options:
          - main
          - develop
          - feature/*
      universe:
        description: 'Universe to deploy'
        default: 'ci'
        type: choice
        options:
          - ci
          - cert
          - anon
          - uat
          - bazaar
                      
      ApiKey:
        description: 'API Key value'
        type: string
        required: true
        
      AccessToken:
        description: 'Access Token value' 
        type: string
        required: true
        
      DatadogKey:
        description: 'Datadog Key value'
        type: string
        required: true


  
env:
  # ENVIRONMENT_TAG: ${{ steps.get_vpc_data.outputs.vpc_data[github.event.inputs.universe] }}
  STACK_NAME: ${{github.event.inputs.universe}}-emoji-secret
  AWS_REGION: us-east-1
  TEAM: emodb-dev@bazaarvoice.com
  SERVICE: emoji
  DATATYPE: client+personal
  
permissions:
  id-token: write
  contents: read

jobs:
  retrieve_stk_info:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install jq
      - name: environment_print
        run: echo ${{github.event.inputs.universe}}
      - name: branch_print
        run: echo ${{github.event.inputs.branch}}
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::549050352176:role/emojigitrole
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy Secrets
        run: |
          cd ops/cfn
          aws cloudformation deploy \
            --stack-name ${{ env.STACK_NAME }} \
            --template-file secrets.cfn.yml \
            --region ${{ env.AWS_REGION }} \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset \
            --parameter-overrides \
              Universe=${{ github.event.inputs.universe}} \
              AccessToken=${{github.event.inputs.AccessToken }} \
              DatadogKey=${{ github.event.inputs.DatadogKey }} \
              ApiKey=${{github.event.inputs.ApiKey }} \
            --tags \
              bv:nexus:team=${{ env.TEAM }} \
              bv:nexus:vpc=${{ env.ENVIRONMENT_TAG }} \
              bv:system=emodb \
              bv:nexus:service=${{ env.SERVICE }} \
              bv:nexus:owner=${{ env.TEAM }} \
              bv:nexus:costcenter=${{ env.TEAM }} \
              bv:nexus:datatype=${{ env.DATATYPE }} \
              bv:nexus:env=${{ env.ENVIRONMENT_TAG }}