name: Deploy Emoji

on:
  workflow_dispatch:
    inputs:
      Universe:
        description: 'Universe to deploy'
        default: 'ci'
        type: choice
        options: [ci, cert, anon, uat, bazaar]
        required: true

      ApiKey:
        description: 'API Key value'
        type: string
        required: true

      AccessToken:
        description: 'Access Token value'
        type: string
        required: true
        
jobs:
  deploy:
    uses: ./.github/workflows/Librarydeploy.yml
    with:
      Universe: ${{ github.event.inputs.Universe }}
      ApiKey: ${{ github.event.inputs.ApiKey }}
      AccessToken: ${{ github.event.inputs.AccessToken }}