name: main_branch_WF

on: 
    workflow_dispatch:
      
jobs:
  setting_up_Default_manual_workflow_with_inputs:
    runs-on: ubuntu-latest
    steps:
        - name: Set up Manual workflow for emojbranch
          run: echo "main branch"
        