name: Deploy Emoji

on:
  workflow_dispatch:
    inputs:
      Universe:
        description: 'Universe to deploy'
        default: 'ci'
        type: choice
        options: [ci, cert, anon, uat, bazaar]
        required: true

      aws_environment:
        description: 'Which environment to deploy'
        default: 'QA'
        type: choice
        options: [QA, PROD]
        required: true

      ApiKey:
        description: 'API Key value'
        type: string
        required: true

      AccessToken:
        description: 'Access Token value'
        type: string
        required: true

env:
  SERVICE: emoji

jobs:
  deploy:
    uses: kpnssreeram/Library/.github/workflows/Librarydeploy.yml@main
    with:
      Universe: ${{ github.event.inputs.Universe }}
      aws_environment: ${{ github.event.inputs.aws_environment }}
      ApiKey: ${{ github.event.inputs.ApiKey }}
      AccessToken: ${{ github.event.inputs.AccessToken }}
