name: emoji_branch_WF

on: 
    workflow_dispatch:
        inputs:
          envron_id:
            description: 'Choose proper universe to deploy ["ci","cert","anon","uat","bazaar"]'
            required: true
      


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - name: environment_print
          run: echo ${{github.event.inputs.envron_id}}
    