name: Deploy internal load balancer

on:
  workflow_dispatch:
    inputs:
      Universe:
        description: 'Universe to deploy'
        default: 'ci'
        type: choice
        options: [ci, cert, anon, uat, bazaar]
        required: true
      DnsSuffix:
        description: Use for testing purposes. Leave blank for real universes
        default: ''

jobs:
  call-internal-alb-lib:
    uses: ./.github/workflows/internal-alb-lib.yml
    with:
      Universe: ${{ inputs.Universe }}
      DnsSuffix: ${{ inputs.DnsSuffix }}

  slacknotify:
    runs-on: ubuntu-latest
    needs: call-internal-alb-lib
    steps:
      - name: Alert to slack
        uses: 8398a7/action-slack@v3
        if: ${{ always() }}
        with:
          status: ${{ needs.call-internal-alb-lib.outputs.firstword }}
          fields: repo,message,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
