name: Deploy internal-alb
on: 
    workflow_dispatch:
        inputs:
            Universe:
                description: 'Universe to deploy'
                default: 'ci'
                type: choice
                options: [ci, cert, anon, uat, bazaar]
                required: true
            ApiKey:
                description: 'API Key value'
                type: string
                required: true
            AccessToken:
                description: 'Access Token value'
                type: string
                required: true
            AWS_REGION:
                description: 'AWS region to deploy'
                default: 'us-east-1'
                type: choice
                options: [us-east-1]

permissions:
    id-token: write
    contents: read
    actions: read
                  
jobs:
  deploy-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Checkout repository with library file
        uses: actions/checkout@v3
        with:
          repository: kpnssreeram/Library
          path: libscript

      - name: Fetch data (deploy label)
        run: |
            label=$(python ./libscript/EmojiLib.py getVpcByUniverse "${{inputs.Universe}}")
            account_id=$(python ./libscript/EmojiLib.py getAccountIdByUniverse "${{inputs.Universe}}")
            echo "Account ID: $account_id"
            echo "Deploy Label: $label"
            echo "EnvTag=$label" >> $GITHUB_ENV
            echo "AccId=$account_id" >> $GITHUB_ENV
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            role-to-assume: arn:aws:iam::${{env.AccId}}:role/emojigitrole
            role-session-name: emojiSecretsSession
            aws-region: ${{ inputs.AWS_REGION }}

      - name: Deploy internal-alb
        run: |
            export AWS_RETRY_MODE="standard"
            export AWS_MAX_ATTEMPTS=15

            aws cloudformation deploy                                   \
            --stack-name ${{ inputs.Universe }}${{ inputs.DnsSuffix }}-emoji-internal-alb-test   \
            --template-file cd ops/cfn/internal-alb.cfn.yml              \
            --parameter-overrides                                     \
                Universe=${{ inputs.Universe }}                                    \
                DnsSuffix=${{ inputs.DnsSuffix }}                                \
            --no-fail-on-empty-changeset                              \
            --tags                                                    \
                bv:nexus:team=$(python ./libscript/EmojiLib.py getTags "team")                                 \
                bv:nexus:vpc=${{env.EnvTag}}                                  \
                bv:system=emodb                                         \
                bv:nexus:service=$(python ./libscript/EmojiLib.py getTags "service")                                \
                bv:nexus:role="internal-elb"                            \
                bv:nexus:owner=$(python ./libscript/EmojiLib.py getTags "team")                                   \
                bv:nexus:access=none                                    \
                bv:nexus:costcenter=$(python ./libscript/EmojiLib.py getTags "team")                              \
                bv:nexus:datatype=$(python ./libscript/EmojiLib.py getTags "datatype")                        \
                bv:nexus:env=${vpc}                                     \
                universe=${{env.EnvTag}}                                   \
            --region ${{inputs.AWS_REGION}}

      - name: Alert to slack
        uses: 8398a7/action-slack@v3
        if: ${{ always() }}
        with:
          status: ${{ job.status }}
          fields: repo,message,job,workflow
          author_name: The workflow at ${{ github.repository }} on branch ${{ github.ref_name }} is ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}