name: Deploy internal load balancer
on:
  workflow_dispatch:
    inputs:
        Universe:
            description: 'Universe to deploy'
            default: ${{readFile('versions.txt')}}
            required: true
        default: $UNIVERSE_VERSION
          env:
            UNIVERSE_VERSION: ${{ github.event.inputs.Universe }}

        DnsSuffix:
            description: Use for testing purposes. Leave blank for real universes
            default: ''
        
jobs:
  call-internal-alb-lib:
    uses: ./.github/workflows/internal-alb-lib.yml
    with:
      Universe: ${{inputs.Universe}}
      DnsSuffix: ${{inputs.DnsSuffix}}
    secrets:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}