name: Deploy internal load balancer

on:
  workflow_dispatch:
    inputs:
      Universe:
        description: 'Universe to deploy'
        default: 'ci'
        type: choice
        options: [ci, cert, anon, uat, bazaar]
        required: true
      DnsSuffix:
        description: Use for testing purposes. Leave blank for real universes
        default: ''

jobs:
  call-internal-alb-lib:
    uses: ./.github/workflows/internal-alb-lib.yml
    with:
      Universe: ${{ inputs.Universe }}
      DnsSuffix: ${{ inputs.DnsSuffix }}

  slacknotify:
    needs: call-internal-alb-lib
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: act10ns/slack@v1
        with:
          status: ${{ needs.call-internal-alb-lib.outputs.firstword }}
          channel: 'emodb-actionsnotify-test'
          message: Deployed {{ env.GITHUB_REF_NAME }} branch Successfully
        if: always()
