name: Deploy Secrets

on:
  workflow_dispatch:
    inputs:
      Universe:
        description: 'Universe to deploy'
        default: 'ci'
        type: choice
        options: [ci, cert, anon, uat, bazaar]
        required: true
      ApiKey:
        description: 'API Key value'
        type: string
        required: true
      AccessToken:
        description: 'Access Token value'
        type: string
        required: true
      AWS_REGION:
        description: 'AWS region to deploy'
        default: 'us-east-1'
        type: choice
        options: [us-east-1]

jobs:
  callSecretsLib:
    uses: ./.github/workflows/secrets-lib.yml
    with:
      Universe: ${{ inputs.Universe }}
      ApiKey: ${{ inputs.ApiKey }}
      AccessToken: ${{ inputs.AccessToken }}
      AWS_REGION: ${{ inputs.AWS_REGION }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
