name: Deploy Secrets

on:
  workflow_dispatch:
    inputs:
      Universe:
        description: 'Universe to deploy'
        default: 'ci'
        type: choice
        options: [ci, cert, anon, uat, bazaar]
        required: true
      ApiKey:
        description: 'API Key value'
        type: string
        required: true
      AccessToken:
        description: 'Access Token value'
        type: string
        required: true

jobs:
  callSecretsLib:
    uses: ./.github/workflows/secrets-lib.yml
    with:
      Universe: ${{ github.event.inputs.Universe }}
      ApiKey: ${{ github.event.inputs.ApiKey }}
      AccessToken: ${{ github.event.inputs.AccessToken }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
